name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      RAW_DATA_PATH: "data/raw"
      PROCESSED_DATA_PATH: "data/processed"
      MODEL_PATH: "models"
      REPORT_PATH: "monitoring/reports"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt pytest httpx

      - run: pytest tests/test_module.py -v

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker containers
        run: docker compose build